# -*- coding: utf-8 -*-

from odoo import api, fields, models
from odoo.tools import SQL, float_is_zero


class ObStockAgeing(models.Model):
    _name = "ob.stock.ageing"
    _description = "Inventory Stock Ageing"
    _order = "age_days desc, received_date, id"

    AGEING_BUCKETS = [
        ("01_0_30", "0 - 30 Days"),
        ("02_31_60", "31 - 60 Days"),
        ("03_61_90", "61 - 90 Days"),
        ("04_91_120", "91 - 120 Days"),
        ("05_over_120", "Over 120 Days"),
    ]

    user_id = fields.Many2one(
        "res.users",
        string="Generated By",
        required=True,
        readonly=True,
        index=True,
        ondelete="cascade",
    )
    company_id = fields.Many2one(
        "res.company",
        required=True,
        readonly=True,
        index=True,
    )
    currency_id = fields.Many2one(
        "res.currency",
        string="Currency",
        required=True,
        readonly=True,
    )
    product_id = fields.Many2one(
        "product.product",
        string="Product",
        required=True,
        readonly=True,
        index=True,
    )
    product_tmpl_id = fields.Many2one(
        "product.template",
        string="Product Template",
        required=True,
        readonly=True,
        index=True,
    )
    product_categ_id = fields.Many2one(
        "product.category",
        string="Product Category",
        readonly=True,
        index=True,
    )
    product_uom_id = fields.Many2one(
        "uom.uom",
        string="Unit of Measure",
        required=True,
        readonly=True,
    )
    stock_move_id = fields.Many2one(
        "stock.move",
        string="Receipt Move",
        required=True,
        readonly=True,
        index=True,
        ondelete="cascade",
    )
    reference = fields.Char(readonly=True)
    received_date = fields.Date(
        string="Receipt Date",
        required=True,
        readonly=True,
        index=True,
    )
    age_days = fields.Integer(
        string="Age (Days)",
        required=True,
        readonly=True,
    )
    ageing_bucket = fields.Selection(
        selection=AGEING_BUCKETS,
        string="Ageing Bucket",
        required=True,
        readonly=True,
        index=True,
    )
    remaining_qty = fields.Float(
        string="Remaining Quantity",
        digits="Product Unit of Measure",
        required=True,
        readonly=True,
    )
    remaining_value = fields.Monetary(
        string="Remaining Value",
        currency_field="currency_id",
        required=True,
        readonly=True,
    )

    @api.model
    def _get_ageing_bucket(self, age_days):
        if age_days <= 30:
            return "01_0_30"
        if age_days <= 60:
            return "02_31_60"
        if age_days <= 90:
            return "03_61_90"
        if age_days <= 120:
            return "04_91_120"
        return "05_over_120"

    @api.model
    def _prepare_report_line(self, company, product, move, remaining_qty, today):
        received_date = fields.Date.to_date(move.date)
        age_days = max((today - received_date).days, 0)
        if product.cost_method == "fifo":
            remaining_value = (
                remaining_qty / move.quantity * move.value
                if move.quantity
                else 0.0
            )
        else:
            remaining_value = remaining_qty * product.standard_price

        return {
            "user_id": self.env.user.id,
            "company_id": company.id,
            "currency_id": company.currency_id.id,
            "product_id": product.id,
            "product_tmpl_id": product.product_tmpl_id.id,
            "product_categ_id": product.categ_id.id,
            "product_uom_id": product.uom_id.id,
            "stock_move_id": move.id,
            "reference": move.reference,
            "received_date": received_date,
            "age_days": age_days,
            "ageing_bucket": self._get_ageing_bucket(age_days),
            "remaining_qty": remaining_qty,
            "remaining_value": remaining_value,
        }

    @api.model
    def _get_remaining_stock_layers(self):
        company_ids = tuple(self.env.companies.ids)
        if not company_ids:
            return []

        self.env["stock.quant"].flush_model([
            "company_id",
            "location_id",
            "owner_id",
            "product_id",
            "quantity",
        ])
        self.env["stock.move"].flush_model([
            "company_id",
            "date",
            "is_in",
            "product_id",
            "quantity",
            "state",
        ])
        self.env["stock.move.line"].flush_model([
            "company_id",
            "location_dest_id",
            "location_id",
            "move_id",
            "owner_id",
            "picked",
            "quantity_product_uom",
        ])

        return self.env.execute_query(SQL("""
            WITH quant_stock AS (
                SELECT
                    quant.company_id,
                    quant.product_id,
                    SUM(quant.quantity) AS on_hand_qty
                FROM stock_quant quant
                JOIN stock_location location
                    ON location.id = quant.location_id
                JOIN res_company company
                    ON company.id = quant.company_id
                JOIN product_product product
                    ON product.id = quant.product_id
                JOIN product_template template
                    ON template.id = product.product_tmpl_id
                WHERE quant.company_id IN %s
                    AND location.company_id = quant.company_id
                    AND location.usage IN ('internal', 'transit')
                    AND (
                        quant.owner_id IS NULL
                        OR quant.owner_id = company.partner_id
                    )
                    AND product.active = TRUE
                    AND template.is_storable = TRUE
                GROUP BY quant.company_id, quant.product_id
                HAVING SUM(quant.quantity) > 0
            ),
            valued_moves AS (
                SELECT
                    move.id AS move_id,
                    move.company_id,
                    move.product_id,
                    move.date,
                    move.quantity AS move_qty,
                    stock.on_hand_qty,
                    SUM(move_line.quantity_product_uom) AS valued_qty
                FROM quant_stock stock
                JOIN stock_move move
                    ON move.company_id = stock.company_id
                    AND move.product_id = stock.product_id
                    AND move.state = 'done'
                    AND move.is_in = TRUE
                JOIN res_company company
                    ON company.id = move.company_id
                JOIN stock_move_line move_line
                    ON move_line.move_id = move.id
                    AND move_line.picked = TRUE
                JOIN stock_location source
                    ON source.id = move_line.location_id
                JOIN stock_location destination
                    ON destination.id = move_line.location_dest_id
                WHERE (
                        move_line.owner_id IS NULL
                        OR move_line.owner_id = company.partner_id
                    )
                    AND NOT (
                        source.company_id IS NOT NULL
                        AND source.usage IN ('internal', 'transit')
                    )
                    AND destination.company_id IS NOT NULL
                    AND destination.usage IN ('internal', 'transit')
                GROUP BY
                    move.id,
                    move.company_id,
                    move.product_id,
                    move.date,
                    move.quantity,
                    stock.on_hand_qty
                HAVING SUM(move_line.quantity_product_uom) > 0
            ),
            ranked_moves AS (
                SELECT
                    valued_moves.*,
                    COALESCE(
                        SUM(valued_qty) OVER (
                            PARTITION BY company_id, product_id
                            ORDER BY date DESC, move_id DESC
                            ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
                        ),
                        0
                    ) AS newer_qty,
                    ROW_NUMBER() OVER (
                        PARTITION BY company_id, product_id
                        ORDER BY date, move_id
                    ) AS oldest_move_number
                FROM valued_moves
            )
            SELECT
                company_id,
                product_id,
                move_id,
                CASE
                    WHEN newer_qty + valued_qty >= on_hand_qty
                        OR oldest_move_number = 1
                    THEN LEAST(valued_qty, on_hand_qty - newer_qty)
                    ELSE move_qty
                END AS remaining_qty
            FROM ranked_moves
            WHERE newer_qty < on_hand_qty
            ORDER BY company_id, product_id, date, move_id
        """, company_ids))

    @api.model
    def _refresh_report(self):
        report = self.sudo()
        report.search([("user_id", "=", self.env.user.id)]).unlink()

        today = fields.Date.context_today(self)
        values = []
        rows_by_company = {}
        for company_id, product_id, move_id, remaining_qty in self._get_remaining_stock_layers():
            rows_by_company.setdefault(company_id, []).append(
                (product_id, move_id, remaining_qty)
            )

        for company in self.env.companies:
            company_rows = rows_by_company.get(company.id, [])
            if not company_rows:
                continue

            products = self.env["product.product"].browse(
                {row[0] for row in company_rows}
            ).with_company(company)
            moves = self.env["stock.move"].browse({row[1] for row in company_rows})
            products.fetch([
                "categ_id",
                "cost_method",
                "product_tmpl_id",
                "standard_price",
                "uom_id",
            ])
            moves.fetch(["date", "quantity", "reference", "value"])
            products_by_id = {product.id: product for product in products}
            moves_by_id = {move.id: move for move in moves}

            for product_id, move_id, remaining_qty in company_rows:
                product = products_by_id[product_id]
                rounding = product.uom_id.rounding
                if float_is_zero(remaining_qty, precision_rounding=rounding):
                    continue
                values.append(
                    self._prepare_report_line(
                        company,
                        product,
                        moves_by_id[move_id],
                        remaining_qty,
                        today,
                    )
                )

        if values:
            report.create(values)

    @api.model
    def action_open_report(self):
        self.check_access("read")
        self._refresh_report()
        action = self.env["ir.actions.actions"]._for_xml_id(
            "ob_stock_ageing.action_ob_stock_ageing"
        )
        action["domain"] = [("user_id", "=", self.env.user.id)]
        return action
